### PR TITLE
Uprev libsettings submodule[CPP-684]

### PR DESCRIPTION
**Pull request by john-michaelburke**
Any chance reviewer could publish this once merged? I upreved the release number.

### CODE REVIEW

**Review by silverjam — APPROVED** [review]

**Comment by john-michaelburke** [comment]
@silverjam Any chance you could publish `0.6.5` to crates.io for me.

**Comment by silverjam** [comment]
No at a computer at the moment, but can take care of it in 15 minutes or so

**Comment by silverjam** [comment]
> @silverjam Any chance you could publish `0.6.5` to crates.io for me.

Can you register on crates.io? I can make you a publisher.

**Comment by john-michaelburke** [comment]
> > @silverjam Any chance you could publish `0.6.5` to crates.io for me.
> 
> Can you register on crates.io? I can make you a publisher.

Sounds good there is no rush. And done, just registered on crates.io

**Comment by silverjam** [comment]
Alright, sent an invite

**Pull request merged**
